import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Metageeks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <link
            rel="stylesheet"
            href="/fonts/your-font.otf"
            type="font/otf"
            as="font"
            crossOrigin="anonymous"
          />
        {/* <div className="p-8"><Header /></div> */}
        {children}
        {/* <div><Footer /></div> */}
      </body>
      
    </html>
  );
}
